ALTER TABLE products
ADD COLUMN content_list TEXT AFTER description,
ADD COLUMN meta VARCHAR(255) AFTER content_list,
ADD COLUMN accent_color VARCHAR(20) AFTER brand,
ADD COLUMN badge_recommended TINYINT(1) DEFAULT 0 AFTER accent_color,
ADD COLUMN tutorial_link VARCHAR(255) AFTER badge_recommended,
ADD COLUMN status VARCHAR(50) AFTER price,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
